services:
  client:
    build:
      context: ./Client
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - server

  server:
    build:
      context: ./Server
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000

