version: "3.9"

services:
  server:
    image: hashir001/ijarahub:server-latest
    container_name: ijara-server
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  client:
    image: hashir001/ijarahub:client-latest
    container_name: ijara-client
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    depends_on:
      server:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s