version: "3.9"

services:
  server:
    image: hashir001/ijarahub-server
    container_name: ijara-server
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
    restart: always

  client:
    image: hashir001/ijarahub-client
    container_name: ijara-client
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    depends_on:
      - server
    restart: always
