name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Client deps
        working-directory: Client
        run: npm ci || npm install

      - name: Lint Client
        working-directory: Client
        run: npm run lint --if-present

      - name: Build Client
        working-directory: Client
        run: npm run build

      - name: Install Server deps
        working-directory: Server
        run: npm ci || npm install

      - name: Build Server
        working-directory: Server
        run: npm run build

      - name: Docker Buildx setup
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        run: |
          docker build -t ijara-hub-client ./Client
          docker build -t ijara-hub-server ./Server

