name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push Client image
        run: |
          docker build -t hashir001/ijarahub:client ./Client
          docker push hashir001/ijarahub:client

      - name: Build and push Server image
        run: |
          docker build -t hashir001/ijarahub:server ./Server
          docker push hashir001/ijarahub:server

  deployaws:
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: Pull latest images
        run: |
          docker pull hashir001/ijarahub:server
          docker pull hashir001/ijarahub:client

      - name: Stop old containers
        run: |
          docker rm -f ijara-server || true
          docker rm -f ijara-client || true

      - name: Run containers using docker-compose
        run: |
          docker-compose -f ./docker-compose.yml up -d --remove-orphans

      # - name: Deploy to AWS EC2 via SSH
      #   uses: appleboy/ssh-action@v0.1.10
      #   with:
      #     host: ${{ secrets.EC2_HOST }}
      #     username: ubuntu
      #     key: ${{ secrets.EC2_SSH_KEY }}
      #     script: |
      #       cd /home/ubuntu/Ijara-hub
      #       git pull origin main
      #       docker-compose pull
      #       docker-compose up -d
