name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push Client image
        run: |
          docker build -t hashir001/ijarahub:client ./Client
          docker push hashir001/ijarahub:client

      - name: Build and push Server image
        run: |
          docker build -t hashir001/ijarahub:server ./Server
          docker push hashir001/ijarahub:server

      - name: Deploy to AWS EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/Ijara-hub
            git pull origin main
            docker-compose pull
            docker-compose up -d
